[build]
  base = "frontend"
  command = "npm run build-frontend"
  publish = "frontend/.next"

[build.environment]
  NODE_VERSION = "20.13.1"
  BACKEND_URL = "https://your-backend-service.com"
  NODE_OPTIONS = "--max_old_space_size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"
