[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.13.1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs@4.39.5"

[context.production.environment]
  NODE_ENV = "production"
