name: Deploy to Production

on:
  push:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci

      - name: Run backend tests
        working-directory: backend
        env:
          NODE_ENV: test
          MONGO_URI: mongodb://root:password@localhost:27017/robovestx_test?authSource=admin
        run: npm test

      - name: Run frontend tests
        working-directory: frontend
        run: |
          npm run build
          npm run test:ci

      - name: Run E2E tests
        working-directory: frontend
        run: npx cypress run

      - name: Build and deploy to production
        if: success()
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          script: |
            cd /var/www/robovestx
            git pull origin main
            cd backend && npm ci --production
            cd ../frontend && npm ci --production
            npm run build
            pm2 restart robovestx
